# Generated by Django 3.2.7 on 2021-09-18 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_create_shop_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('GTIN', models.CharField(max_length=14, unique=True)),
                ('expiry_date', models.DateField()),
                (
                    'shop',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='stock_readings', to='shop.shop'
                    ),
                ),
            ],
        ),
    ]
